Use same lumen technique to navigate clj code with cider/emacs
akvo/akvo-flow-services pull request #303
Opened 2021-02-22 12:57 UTC by tangrammer

2021-02-25 11:55 UTC, iperdomo requested changes
CIDER introduced a *custom variable* to do the path translation automatically. We don't need to maintain custom elisp code. https://docs.cider.mx/cider/config/basic_config.html#translate-file-paths

The only problem is that the documentation doesn't explain it how to do it for a team of developers that have the Clojure project in different locations.

I managed to solve it using `eval` *pseudo-variable* to configure `cider-path-translations` dynamically.

Can you please try this locally and check if this works on your machine?
https://gist.github.com/iperdomo/88f3156dbb79fe99bc440d1700bb7162

If it works I would suggest to update the PR and perhaps change `akvo-lumen` and other repositories.

NOTE: The *gist* also fixes a problem of translating `/home/akvo/.m2` -> host's `m2`, something the custom elisp is not doing (AFAIK)

2021-03-01 08:42 UTC, tangrammer commented
@iperdomo your `.dir-locals.el` works perfectly fine in my emacs

I saw that you commited the code to CIDER already 🥳 !! so the question is do we want to have the script anyway in our repos or just add to the docs that we should upgrade CIDER to have this functionality available?

2021-03-01 13:55 UTC, iperdomo commented
> I saw that you commited the code to CIDER already partying_face !! so the question is do we want to have the script anyway in our repos or just add to the docs that we should upgrade CIDER to have this functionality available?

What I contributed was documentation, CIDER will not do anything *automagically*. We do want to have that copy of `.dir-locals.el` for our repos.

2021-03-02 08:23 UTC, iperdomo approved these changes

2021-03-02 08:23 UTC, merged